import { useState } from 'react';
import { Copy, Mail } from 'lucide-react';
import Button from './ui/Button';
import Card from './ui/Card';

const EmailHandoff = ({ pulse, onEmailSent }) => {
  const [copied, setCopied] = useState(false);

  const buildEmailBody = (pulseData) => {
    const { week, pulse: pulseContent } = pulseData;
    const { top_themes, action_ideas } = pulseContent;

    let body = `TOP THEMES

`;

    top_themes.forEach((theme, index) => {
      body += `${index + 1}. ${theme.name} (${theme.review_count} reviews · ${theme.sentiment})
   ${theme.description}
   "${theme.user_quote}"

`;
    });

    body += `ACTION IDEAS

`;

    action_ideas.forEach((idea, index) => {
      body += `${index + 1}. ${idea}
`;
    });

    body += `
— Generated by Groww Pulse Tool`;

    return body;
  };

  const handleOpenGmail = () => {
    const body = buildEmailBody(pulse);
    const subject = `Groww Weekly Pulse — ${pulse.week}`;
    const gmailComposeUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(gmailComposeUrl, '_blank', 'noopener,noreferrer');
    onEmailSent();
  };

  const handleCopyToClipboard = async () => {
    const body = buildEmailBody(pulse);
    try {
      await navigator.clipboard.writeText(body);
      setCopied(true);
      onEmailSent();
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const emailBody = buildEmailBody(pulse);

  return (
    <div className="space-y-6">
      <Card className="p-6">
        <div className="mb-6">
          <h3 className="text-lg font-semibold tracking-tight text-text-primary mb-2">
            Email Preview
          </h3>
          <p className="text-sm text-text-secondary">
            This is exactly what will be sent in the email:
          </p>
        </div>

        <div className="mb-6">
          <div className="bg-background-tertiary border border-border rounded-lg p-4 max-h-96 overflow-y-auto">
            <pre className="font-mono text-xs text-text-primary whitespace-pre-wrap">
              {emailBody}
            </pre>
          </div>
        </div>

        <div className="flex gap-4">
          <Button
            onClick={handleOpenGmail}
            className="flex items-center gap-2"
          >
            <Mail className="w-4 h-4" />
            Open in Gmail
          </Button>
          <Button
            variant="secondary"
            onClick={handleCopyToClipboard}
            className="flex items-center gap-2"
          >
            <Copy className="w-4 h-4" />
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default EmailHandoff;
